### ISSUE TITLE
Extensionality axioms for datatypes

### ISSUE THREAD

**Issue by jaylorch** [Microsoft/dafny#133]
Dafny can’t verify the lemma below unless I uncomment the comment. To deal with examples like this, it would be nice if Dafny used extensionality axioms for datatypes as it currently does for sets, multisets, maps, and sequences.

datatype State = State(m:map<int, bool>)

lemma Test(s:State)
    requires 42 in s.m
    ensures  s.(m := s.m[42 := s.m[42]]) == s
{
    var s' := s.(m := s.m[42 := s.m[42]]);
//    assert s'.m == s.m;
}

I discussed this with Rustan, and he thinks this feature could potentially be added. Below is what he said about the matter....

Perhaps like this (for this example):

  axiom (forall S,S’ :: State#Equal(S,S’) <==> m(S) == m(S’));
  axiom (forall S,S’ :: State#Equal(S,S’) ==> S == S’);

In fact, it would then be nice (I think) to use an #Equals function one level down as well.  That is, the axioms would actually be:

  axiom (forall S,S’ :: State#Equal(S,S’) <==> Set#Equals(m(S), m(S’)));   // use of Set#Equals here instead of ==
  axiom (forall S,S’ :: State#Equal(S,S’) ==> S == S’);

**Comment by wilcoxjay** [comment]
I briefly experimented with this example at the Boogie level and found that using `Map#Equal` instead of `==` in the axioms is essential to making things work. I believe this is because `Map#Equal` is a trigger for much of the map axioms.

**Comment by wilcoxjay** [comment]
I have started prototyping this [here](https://github.com/Microsoft/dafny/compare/master...wilcoxjay:datatype-extensionality).

I'm running into several performance problems. 

First, there was a problem with using generating axioms for extensional equality on recursive types, which would introduce a matching loop. I decided to make immediately recursive instances use `==` instead, and this seems to be working well. But I haven't figured out how to make indirectly recursive uses work correctly yet (eg, a constructor with a field that is a pair of recursive calls).

Second, there is a problem with the disjunction connecting the top-level datatype equality function `Dt#Equal` to each constructor's equality function `Dt.Ci#Equal`. I currently have this triggered on `Dt#Equal`, but Z3 seems to be overzealously applying it. One rather extreme approach here would be to only generate extensionality axioms for datatypes with a single constructor. Another idea would be to trigger them on something else, perhaps the question-mark function `Dt.Ci?`. Then, instead of having to enumerate fields in that case, the user would just have to assert which constructor one of the values had.

@jaylorch Would just supporting single-constructor types work for your use case?

**Comment by jaylorch** [comment]
For the use case that I was working on when I encountered this issue, single-constructor types would be sufficient. And I think this would be rather generally useful.

But it might be nice, in the future, to have the option of using them for multi-constructor types, perhaps with using the question-mark function as a trigger as you suggest.

**Comment by wilcoxjay** [comment]
This change occasionally interacts poorly with some cases of Dafny's induction heuristic.

Consider the following lemma, from `Test/dafny4/ACL2-extractor.dfy`
```
lemma EqualElementsMakeEqualLists(xs: List, ys: List)
  requires length(xs) == length(ys)
  requires forall i :: 0 <= i < length(xs) ==> nth(i, xs) == nth(i, ys)
  ensures xs == ys
{
  match xs {
    case Nil =>
    case Cons(_, _) =>
      assert nth(0, xs) == nth(0, ys);
      forall i | 0 <= i < length(xs.tail) { ... }
     //EqualElementsMakeEqualLists(xs.tail, ys.tail);
}
```
where I have elided the irrelevant body of the `forall` statement. Note that the proof does not make an explicit recursive call (in other words, the commented out call is not needed).

In Dafny today, the induction heuristic will insert an induction hypothesis into the body of this method that looks something like this at the Boogie level:
```
forall ihxs, ihys :: 
  && (Rank(ihxs) < Rank(xs) || (Rank(ihxs) == Rank(xs) && Rank(ihys) < Rank(ys)) 
  && PRE(ihxs, ihys) 
  ==> ihxs == ihys
```
where `PRE` represents the preconditions of `EqualElementsMakeEqualLists`.

Notice that this quantifier is not explicitly triggered. Z3 infers the trigger `{Rank(ihxs), Rank(ihys)}`, which turns out to be a reasonable idea, because there are axioms connecting `Cons` and `Rank`.

Under the datatype extensionality prototype, the induction hypothesis looks like this, instead:
```
forall ihxs, ihys :: 
  && (Rank(ihxs) < Rank(xs) || (Rank(ihxs) == Rank(xs) && Rank(ihys) < Rank(ys)) 
  && PRE(ihxs, ihys) 
  ==> List#Equals(ihxs, ihys)
```
Now when Z3 does trigger inference, it chooses the new option, `{List#Equals(ihxs, ihys)}`. Unfortunately, this is not such a good idea, because the only axiom connecting `Cons` and `List#Equals` does not use `List#Equals` on the tail. This results in the proof not going through. The proof can be fixed either by making an explicit recursive call, or by asserting `xs.tail == ys.tail`, since that gets translated into `List#Equals`, which matches the inferred trigger. 

What do people think about this? I can think of a few options:
* Live with the fact that datatype extensionality changes what can be proved by induction, do to the fact that new (sometimes not useful) triggers are available for Z3 to infer.
* Adjust the `List#Equals` axioms to support "extensional unrolling" up to a certain depth for recursive types, similar to the way recursive functions are currently encoded in Boogie.
* Find a way for Dafny to generate explicit triggers on induction hypotheses, and solve this problem as a side effect.
