### ISSUE TITLE
Method and constructor calls are not properly checked for export visibility

### ISSUE THREAD

**Issue by wilcoxjay** [Microsoft/dafny#142]
Consider the following program.
```
module M {
    export provides C

    class C {
        constructor() {
        }
    }
}

module Main {
    import M

    method Main() {
        var x := new M.C();
    }
}
```

Dafny reports an internal translation error:
```
call to undeclared procedure: Call$$_0_M.C.__ctor
```

Instead, there should be an error at the call site that C's constructor is not in scope.

This issue is still present even if we give the constructor an explicit name. But, adding it to the export list resolves the issue as expected.

EDIT: upon further investigation, this appears to have nothing to do with constructors, but instead affects methods as well.

**Comment by qunyanm** [comment]
Seems to be fixed in the latest version. The error messages it generates are:
git-issue142.dfy(17,17): Error: member '_ctor' has not been imported in this scope and cannot be accessed here
git-issue142.dfy(17,17): Error: type C? does not have a member _ctor
git-issue142.dfy(17,14): Error: when allocating an object of type 'C', one of its constructor methods must be called
