### ISSUE TITLE
Parse problem for set-expressions in calculations

### ISSUE THREAD

**Issue by jiplucap** [Microsoft/dafny#152]
It seems that a curly bracket after the operator means "hint", but sometimes could be a set-expression.
See  https://rise4fun.com/Dafny/bdiPC

**Comment by wilcoxjay** [comment]
Yes, this is a known ambiguity in the grammar.

The behavior you observe is intended, even though it is not exactly ideal. 

The usual workaround for this is to parenthesize the offending expression, as in:
```
calc {
    {1,2,3} + s;
    ==
    ({1} + {2,3} + s);
}
```
which works correctly.

PS: By the way, if you are interested, this would be a good question to ask on StackOverflow, so that it is easier for people in the future to Google it even after we close this issue. Thanks!
