### ISSUE TITLE
Unexpected effects of {:opaque}

### ISSUE THREAD

**Issue by ningit** [Microsoft/dafny#154]
Consider the following code:

```
function {:opaque} Pow(x : real, n : nat) : real
{
	if n == 0 then 1.0 else x * Pow(x, n-1)
}

method Limit(x : real, e : real) returns (k0 : nat)
	requires 0.0 <= x < 1.0
	requires e > 0.0

	ensures forall k | k >= k0 :: Pow(x, k) < e

method Test()
{
	var x := 0.5;
	var e := 0.001;

	var k0 := Limit(x, e);

	assert forall k | k >= k0 :: Pow(x, k) < e;
}
```

Dafny reports an assertion violation in the `assert` statement of the `Test` method, even though its formula is literally the postcondition of the method called just before.

However, if `{:opaque}` is removed from the `Pow` definition, no verification errors appeared.

**Comment by wilcoxjay** [comment]
This strange behavior comes from a triggering problem related to opaque functions. I will give a detailed explanation for this behavior as well as a workaround to achieve opacity without this problem. You may wish to skip the explanation of the strange behavior if you only care about getting your program to work with an opaque `Pow` function.

## The explanation

In Dafny, the `{:opaque}` attribute is implemented via "fuel", which introduces an additional parameter to the function that controls when the function's definition may be used. Unfortunately, this translation can cause problems when the function is used as the trigger for a quantifier. When there are several different values of the fuel parameter floating around, the quantifier may not get instantiated correctly.

This can be seen by examining the Boogie output for your test program (via the `/print:foo.bpl` option). The `Limit` method's postcondition gets translated to:

```
procedure Limit(x: real, e: real) returns (k0: int);
  // ...
  ensures 
      (forall k: int :: 
          { Pow(StartFuel.Pow, x, k) } 
        k >= k0
        ==> 
        Pow(StartFuel.Pow, x, k) < e);
```

While the `assert` inside `Test` gets translated to:

```
assert
    (forall k: int :: 
        { Pow(StartFuelAssert.Pow, x, k) } 
      k >= k0
      ==> 
      Pow(StartFuelAssert.Pow, x, k) < e);
```
(I have cleaned these translations up slightly by turning off Dafny's induction heuristic, which is irrelevant to this issue. I've also renamed some things for clarity.)

The key thing to notice is that the fuel values passed to `Pow` are different in the two contexts: `StartFuel.Pow` vs `StartFuelAssert.Pow`. (Note that `.` is a valid character in identifier names in Boogie, so these are just two different global constants.) 

Since the first quantifier's trigger mentions one global constant fuel, while the second mentions another, Z3 will not be able to prove that the (logically trivial) implication holds, because it will never instantiate the first quantifier.

I have personally run into this issue with `{:opaque}`, and it has caused me to decide to never use it. I consider it a bug, though I'm not entirely sure what a good fix would be.

## The workaround

Luckily, there is another way to achieve opacity without `{:opaque}`, by using the module system. 

Consider the following modified version of your program:
```
module M {
    export provides Pow, Limit

    function Pow(x : real, n : nat) : real
    {
    	if n == 0 then 1.0 else x * Pow(x, n-1)
    }
    
    method Limit(x : real, e : real) returns (k0 : nat)
    	requires 0.0 <= x < 1.0
    	requires e > 0.0
    
        ensures forall k | k >= k0 :: Pow(x, k) < e
}

module Test {
    import M

    method Test()
    {
    	var x := 0.5;
    	var e := 0.001;
    
        var k0 := M.Limit(x, e);
    
        assert forall k | k >= k0 :: M.Pow(x, k) < e;
    }
}
```

Module `M` defines `Pow` and `Limit` and declares them as `export provides`. For lemmas/methods, this just means that importing modules can use them. For functions, though, it means that they can be used but their definitions are hidden. (You can mark a function `export reveals` instead, if you'd like to export the definition as well.)

The module `Test` imports `M` and the assertion goes through, even though `Pow`'s definition is not exposed. This is because `export provides` implements opacity differently, not via "fuel", so it doesn't interfere with triggering.

When I need to make a function opaque, I do it with the module system. It's a bit more heavyweight (since it requires restructuring your code into modules, instead of just throwing an attribute on the function), but it doesn't have the problems of the `{:opaque}` attribute.

**Comment by ningit** [comment]
Thanks for the workaround and the explanation, that have been useful and interesting.

**Comment by parno** [comment]
Rustan and I worked on a cleaner design for fuel that would, in principle, fix this issue, along with a number of other fuel-related issues.  The main idea was to remove fuel as an argument from the Boogie-version of the Dafny function, and instead pass it as an argument to the corresponding `CanCall` function.  It's a pretty large, cross-cutting change, so unfortunately, neither of us has had a chance to attempt it.
