### ISSUE TITLE
Preconditions for lambdas

### ISSUE THREAD

**Issue by wilcoxjay** [Microsoft/dafny#156]
Consider the following program:

```
function Foo(f: () --> ()): () --> ()
{
    () requires f.requires() => f()
}

function Foo'(f: () --> (), x: ()): ()
    requires f.requires()
{
    f()
}

lemma FooRequires(f: () --> ())
    ensures f.requires() <==> Foo(f).requires()
    ensures f.requires() <==> Foo'.requires(f, ())
{}
```

`Foo` and `Foo'` differ only in currying, but Dafny seems less able to reason about `Foo`. The lemma `FooRequires` fails to prove the first postcondition.

**Comment by RustanLeino** [comment]
This is subtle, but by design. The axioms about `requires` for a lambda don't let you determine the exact precondition, only a sufficient condition for the precondition. If you change `<==>` to `==>` in the line that fails above, it will verify.

The hope behind this design is that you don't need anything more than this.  In fact, if you got equality, then you get an unsoundness, see line 46 of Test/hofs/FnRef.dfy.

  Rustan
