### ISSUE TITLE
Map lookups fail with objects

### ISSUE THREAD

**Issue by alaarman** [Microsoft/dafny#159]
See comments in the code below:

```
class Value {   constructor () {} }

type T = (Value,Value,Value)

function sum(S:seq<real>): real
{
  if S==[] then 0.0 else S[0] + sum(S[1..])
}

function sum1(M:map<Value,real>, S:seq<Value>): real
//reads M,S // crashes with: (0,-1): Error: invalid argument types (ref and Map Box Box) to binary operator ==
requires forall t :: t in S ==> t in M 
{
  if S==[] then 0.0 else M[S[0]] + sum1(M,S[1..])
}

function sum2(M:map<T,real>, S:seq<T>): real
requires forall t :: t in S ==> t in M 
{
  if S==[] then 0.0 else M[S[0]] + sum2(M,S[1..])
}

function sum3(M:map<int,real>, S:seq<int>): real
requires forall t :: t in S ==> t in M 
{
  if S==[] then 0.0 else M[S[0]] + sum3(M,S[1..])
}

method Main()
{
  assert  sum([0.8,0.1,0.1]) == 1.0;
  var D:= new Value(); //DUMMY
  var a1:= new Value( );
  var a2:= new Value( );
  var a3:= new Value( );

  var c1 := map[
                a1 := 0.8,
                a2 := 0.1,
                a3 := 0.1
              ];
  assert  c1[a1]+c1[a2]+c1[a3] == 1.0; 
  assert  sum1(c1,[a1,a2,a3]) == 1.0; // stdin.dfy(36,30): Error: assertion violation

  var c2 := map[
                (D,D,a1) := 0.8,
                (D,D,a2) := 0.1,
                (D,D,a3) := 0.1
              ];
  assert  sum2(c2,[(D,D,a1),(D,D,a2),(D,D,a3)]) == 1.0; // stdin.dfy(44,48): Error: assertion violation


  var c3 := map[
                1 := 0.8,
                2 := 0.1,
                3 := 0.1
              ];
  assert  sum3(c3,[1,2,3]) == 1.0; 
}

```
https://rise4fun.com/Dafny/Ih33

**Comment by RustanLeino** [comment]
Thanks for the bug report. I fixed the crash that was caused by putting a `map` in a `reads` clause. (Maps were not intended to be used in `reads` and `modifies` clauses, but the check for that was omitted. If a map contains information you want to use in a `reads` or `modifies` clause, note that you can use the `.Keys` and `.Values` members of a map, which give you sets.)

As for your other question, your assertions are too advanced for the Dafny verifier to handle automatically. They make use of recursive functions and the Dafny verifier limits how much it's willing to unroll the definition of functions. Such limits are important, because they keep the verifier from unrolling functions forever in situations where a proof obligation does not hold. Therefore, to prove the assertions about `sum1` and `sum2`, you have to provide some guidance to the verifier. This is most easily done with a `calc` statement, see the code below.

The Dafny verifier does unroll functions a little bit (usually once, sometimes twice), or else you wouldn't be able to prove anything. But there are also cases where it would indeed be useful to let Dafny unroll functions much more. Such cases tend to crop up when you write an example to test a function, which is essentially what your assertions above are doing. To handle _some_ such cases automatically, the Dafny verifier uses, under the hood, a "dual encoding" of function definitions. This clever encoding causes the verifier to fully evaluate functions applied to (most) literal arguments. When testing a function by examples, the inputs are often literals, so this functionality is quite useful. Indeed, it is this functionality that causes your `sum3` example to go through automatically, because the arguments passed to `sum3` in your example are all literals. In contrast, `a1`, `a2`, and `a3` do not hold literal values, so the Dafny verifier limits function unrolling involving them. (For more information about the dual encoding, see _Computing with an SMT solver_ by Amin, Leino, and Rompf [TAP 2014].)

  Rustan

```
class Value {   constructor () {} }

type T = (Value,Value,Value)

function sum(S:seq<real>): real
{
  if S==[] then 0.0 else S[0] + sum(S[1..])
}

function sum1(M:map<Value,real>, S:seq<Value>): real
//reads M,S // including this line now produces an error, not a crash
requires forall t :: t in S ==> t in M 
{
  if S==[] then 0.0 else M[S[0]] + sum1(M,S[1..])
}

function sum2(M:map<T,real>, S:seq<T>): real
requires forall t :: t in S ==> t in M 
{
  if S==[] then 0.0 else M[S[0]] + sum2(M,S[1..])
}

function sum3(M:map<int,real>, S:seq<int>): real
requires forall t :: t in S ==> t in M 
{
  if S==[] then 0.0 else M[S[0]] + sum3(M,S[1..])
}

method Main()
{
  assert  sum([0.8,0.1,0.1]) == 1.0;
  var D:= new Value(); //DUMMY
  var a1:= new Value( );
  var a2:= new Value( );
  var a3:= new Value( );

  var c1 := map[
                a1 := 0.8,
                a2 := 0.1,
                a3 := 0.1
              ];
  assert  c1[a1]+c1[a2]+c1[a3] == 1.0; 
  calc {
     sum1(c1,[a1,a2,a3]);
  == c1[a1] + sum1(c1,[a2,a3]);
  == c1[a1] + c1[a2] + sum1(c1, [a3]);
  == 1.0;
  }
  assert  sum1(c1,[a1,a2,a3]) == 1.0; // now verifies, given the calculuation above

  var c2 := map[
                (D,D,a1) := 0.8,
                (D,D,a2) := 0.1,
                (D,D,a3) := 0.1
              ];
  calc {
     sum2(c2,[(D,D,a1),(D,D,a2),(D,D,a3)]);
  == c2[(D,D,a1)] + sum2(c2,[(D,D,a2),(D,D,a3)]);
  == c2[(D,D,a1)] + c2[(D,D,a2)] + sum2(c2,[(D,D,a3)]);
  == 1.0;
  }
  assert  sum2(c2,[(D,D,a1),(D,D,a2),(D,D,a3)]) == 1.0; // now verifies, given the calculuation above


  var c3 := map[
                1 := 0.8,
                2 := 0.1,
                3 := 0.1
              ];
  assert  sum3(c3,[1,2,3]) == 1.0; 
}
```

**Comment by alaarman** [comment]
Thanks for the explanation and rapid fixes.
Can I use calc to reason over arbitrary maps? For example, I want to use sum2()==1.0 in the precondition of some function.

**Comment by alaarman** [comment]
Is there way to use the map directly in the sum function, instead of supplying a sequence? .Keys yields a set, which also does not support selection of single elements. This is why I use the sequence, but constructing for sets is difficult as there is no sequence comprehension.
