### ISSUE TITLE
Spurious unreachable code warning -- compiler internal -- prevents verified code from compiling

### ISSUE THREAD

**Issue by kevinsullivan** [Microsoft/dafny#174]
Here's the error:
dafny seq-test.dfy
Dafny program verifier version 1.9.9.40418, Copyright (c) 2003-2017, Microsoft.

Dafny program verifier finished with 1 verified, 0 errors
Errors compiling program into seq-test.dll
/var/folders/5n/6hml8q9s39300wsyb2kb89b00000gn/T/15c702be/363ec6d8.0.cs(1546,9) : warning CS0162: Unreachable code detected

========

Here's the code:

method setToSeq(s: set<int>, l: seq<int>) returns
    (result: seq<int>)
    decreases s;
{
    if (s == {}) 
    { 
        return  l; 
    } 
    else 
    {
        var v :| v in s;
        result := setToSeq(s - { v }, [v] + l);
        return;
    } 
}

**Comment by RustanLeino** [comment]
Warning 0162 was turned off in commit fbfd7fcf7bce078891eaff8301e2b81544d54a54 [fbfd7fc] from 30 Aug 2017. (However, as a minor point, I noticed that the warning is not mentioned in the comment about warnings in the .cs file that Dafny is able to generate. I just added it.)

It seems worrisome that a warning like this one can cause the compilation to fail (as opposed to just reporting a warning, but still successfully compiling the program). I was not able to reproduce that behavior, even when I temporarily changed the Dafny compiler to omit the switches that disables warnings. I'm guessing this behavior has also changed since version 1.9.9.

  Rustan
