### ISSUE TITLE
Invariant over modified sequence

### ISSUE THREAD

**Issue by alaarman** [Microsoft/dafny#178]
The following example verifies with `invariant v in (set v: V | v in sigma)`, but not with `invariant v in sigma`. I am trying to understand why. Is it because sigma is modified in the recursive call? Is the current approach still correct?

(.Keys and .Values is not listed in the otherwise excellent Dafny manual btw.)

```
type V = int
type EE = map<V,set<V>>
datatype G = Graph(E:EE)

predicate method graph(g:G, v:V)
{
    v in g.E && forall v,w: V | v in g.E && w in g.E[v] :: w in g.E
}

class DepthFirstSearch {
    var sigma: seq<V>;

    method DFS(g:G, v:V)
        requires graph(g,v)
        requires v in g.E
        requires v !in sigma
        modifies this`sigma                 // only modidfies sigma, set g.E remains the same
        decreases g.E.Keys - (set v:V | v in sigma)
        ensures old(sigma) < sigma          // input is (strict) prefix of output sigma
    {
        sigma := sigma + [v];
        var S: set<V> := g.E[v];
        while S != {}                       // iterate over successors S
            decreases S
            invariant old(sigma) <= sigma   // input is prefix of output sigma
            invariant v in (set v: V | v in sigma)
        {
            var w:V :| w in S;              // let w s.t. w in S
            if (w !in sigma) { DFS(g,w); }
            S := S - {w};
        }
    }
}
```

**Comment by wilcoxjay** [comment]
Under the hood, this is another trigger problem between the set comprehension's notion of membership and the sequences notion of membership.

One way to get the other version working is to add the assertion 

    assert v in (set v | v in sigma);

to the top of the body of the loop. Though this is perhaps a little disappointing, since it repeats the alternative invariant.

There is another open issue specifically about documenting `.Keys` and `.Values`, so we wont' forget to do that. I'll close this issue in a few days.
