### ISSUE TITLE
Verifier fails when adding predicate

### ISSUE THREAD

**Issue by alaarman** [Microsoft/dafny#180]
In the following example, relnext1 verifies but relnext2, with minor differences, does not.

```
// relnext1: Simplest version of relnext.
method relnext1(T: set<int>, R: map<int,set<int>>) returns (S: set<int>)
    decreases T
    ensures forall a: int :: a in S <== (exists b: int | b in R :: b in T && a in R[b]) // completeness
    ensures forall a: int :: a in S ==> (exists b: int | b in R :: b in T && a in R[b]) // soundness
{
    if (T == {}) { return {}; }
    var x :| x in T;
    var X: set<int> := relnext1(T - {x}, R);
    if (x in R) {
        return X + R[x];
    } else {
        return X;
    }
}

predicate contains(S: set<int>, x: int) ensures contains(S, x) <==> x in S { x in S }

// relnext2: Added the predicate "contains" which replaces the "in" operator.
// verifier no longer succeeds!
method relnext2(T: set<int>, R: map<int,set<int>>) returns (S: set<int>)
    decreases T
    ensures forall a: int :: contains(S,a) <== (exists b: int | b in R :: b in T && a in R[b]) // completeness
    ensures forall a: int :: contains(S,a) ==> (exists b: int | b in R :: b in T && a in R[b]) // soundness
{
    if (T == {}) { return {}; }
    var x :| x in T;
    assert contains(T,x);
    var X: set<int> := relnext2(T - {x}, R);
    if (x in R) {
        return X + R[x];
    } else {
        return X;
    }
}


```

https://rise4fun.com/Dafny/V5c

**Comment by wilcoxjay** [comment]
This is indeed somewhat unintuitive. But it is part of the price we pay for using Z3's syntactic heuristics for reasoning about quantifiers: sometimes merely syntactic changes to a program can trip up the heuristics.

You can work around this particular example by adding the line 

    assert forall a :: contains(X, a) <==> a in X;

right after the recursive call in `relnext2`.

To understand why this helps, look at the inferred triggers for the quantifiers in the postconditions of each method. For `relnext1`, the trigger is `a in S`. But for `relnext2` the trigger is `contains(S,a)`. This matters because Dafny's built-in axioms about various set theoretic operations are often triggered on `in`. With `contains` as the trigger instead, those axioms will not be invoked, and the verification will fail. 

The assertion I suggested above fixes the problem because (one of) the triggers Dafny infers for it is `a in S`. 

Finally, as an aside, you can express the idea of `relnext` more succinctly as 

    function method relnext3(T: set<int>, R: map<int,set<int>>): (S: set<int>)
    {
        set a, b | b in T && b in R && a in R[b] :: a
    }

though I make no claims as to whether this is better for reasoning, just that it is shorter.
