### ISSUE TITLE
Trivial asserts about sequences fail

### ISSUE THREAD

**Issue by alaarman** [Microsoft/dafny#184]
The following trivial assertions fail in the later versions of Dafny. 
It could be the reason why some published proofs [1] fail in the current version.

```
class C {
    method M()
    {
        var s := [3];
        assert exists p:seq<int> :: |p| < 10; // FAILS if 'var s := [3];' is commented out
        assert |s| > 0;
        assert exists p:seq<int> :: |p| > 0; // FAILS if 'assert |s| > 0;' is commented out

        //assert exists p:seq<int> :: (forall v:int | v in p :: v in {1,2}) && |p| > 0;  // FAILS
        assert exists p:seq<int> :: (forall v:int | v in p :: v in {1,2,3}) && |p| > 0;
    }
}
```

[1] https://research.utwente.nl/en/publications/automated-verification-of-nested-dfs

**Comment by RustanLeino** [comment]
Proving that an existential quantifier holds can be more difficult than it looks. And it is often the simpler-looking existentials that the verifier has trouble with, which may seem extra puzzling or frustrating.

# Providing a witness

To prove an existential, you generally have to provide a witness. In your first two examples, this witness has to have the form `|w|`, where `w` is a sequence that provably satisfies the body of the existential quantifier. Here are some different ways that you can provide a witness to the second quantifier:

```
// Introducing a variable and checking that it has the desired length property.
ghost var s := [3];  // note, if you don't want `s` compiled, you can declare it as ghost
assert |s| > 0;
assert exists p:seq<int> :: |p| > 0;
```

```
// Mentioning a witness without putting it into a variable.
assert |[3]| > 0;
assert exists p:seq<int> :: |p| > 0;
```

```
// Just mentioning the length of an appropriate witness.
ghost var len := |[3]|;
assert exists p:seq<int> :: |p| > 0;
```

```
// Confining the mention of the witness and its properties to a `by`-clause.
assert exists p:seq<int> :: |p| > 0 by {
  assert |[3]| > 0;
}
```

```
// Adding another conjunct that asserts the property about the witness
assert |[3]| > 0 && exists p:seq<int> :: |p| > 0;
```

```
// Using an `assert` expression. (Note, the outer `assert` in this example is an
// `assert` statement, the inner is an `assert` expression.) This can be useful
// if the existential quantifier you're trying to prove is in the middle of another
// expression.
assert
  assert |[3]| > 0;
  exists p:seq<int> :: |p| > 0;
```

Following one of these patterns, you can prove the third assertion like this:

```
assert exists p:seq<int> :: (forall v:int | v in p :: v in {1,2}) && |p| > 0 by {
  assert |[1,2]| == 2;
}
```

# Simple properties are difficult

If the property you're trying to establish uses only arithmetic or only equality, then it's more difficult to exhibit the witness. For example, if you try an assertion like:

```
assert exists x :: x > 6;
```

you'll have a hard time providing the witness in a way that the verifier will think of using correctly. This is why "more complicated" examples are easier to work with.

# Why the second example is different than the first

The first two examples seem quite similar, so why is it that the first only needs the definition of `s` whereas the second also needs the mention of `|s|`? Both actually need a mention of the length of the witness. As a detail of the current internal encoding of sequences in the Dafny verifier, the sequence `[3]` is constructed from the simpler sequence `[]`, and it so happens that the verifier has the length of that empty sequence "lying around". But in general, you should expect to have to supply the witness for both of the quantifiers.

I will look into making sure the length of all mentioned sequence displays, like `[3]`, is "lying around". However, it may be that this causes a performance degradation in other common cases, so you may need to continue mentioning `|[3]|` explicitly, as opposed to just mentioning `[3]`.

# Assign-such-that statements

There is one place where the Dafny verifier tries to help you find simple witnesses, namely in the assign-such-that statement and the let-such-that expression. For example, if you assign to a local variable `q` an arbitrary value that satisfies `|q| > 0`, then the verifier gets it!

```
// In the following, the verifier has to prove that there exists a `q` with the property
// `|q| < 10`, after which `q` will be assigned some such value.
var q:seq<int> :| |q| < 10;
```

The reason for this is that Dafny tries some simple witnesses for these, including the empty sequence. I actually thought that this simple-witness guessing was implemented also for existential quantifiers in general, but it is implemented only for the `:|` constructs. This could change. (Again, we'd have to consider the performance impact on other programs with existentials.) So again, expect to have to supply a witness in order to establish an existential quantifier.

  Rustan
