### ISSUE TITLE
Enum in arrays

### ISSUE THREAD

**Issue by layus** [Microsoft/dafny#192]
Dafny is not able to prove the third lemma here without the `complete_enum` lemma. It seems that it is related to the use of arrays, even tough we only use e[0] in the lemma.

Is there something special about this code that could explain Dafny's failure ?

I would expect such a simple assertion to pass trivially.

```
datatype Enum = A | B | C

lemma complete_enum(e: Enum)
    ensures e == A || e == B || e == C
{ }

lemma mwe(e: Enum) 
    ensures e != A ==> e == B || e == C
{ }

lemma mwe_array(e: array<Enum>)
    requires e.Length > 0
    ensures e[0] != A ==> e[0] == B || e[0] == C
{
    //complete_enum(e[0]); // This is needed. Why ?
}
```

**Comment by wilcoxjay** [comment]
This is indeed somewhat surprising. The reason `mwe_array` and `mwe` are different (to Dafny) is that the former reads the heap (by indexing into the array), while the latter does not. Reading the heap makes the encoding to the solver more convoluted, and it isn't able to connect the dots.

In general, you will get better performance from using datatypes if you use the builtin predicates `e.A?` instead of saying `e == A`. If you make this transformation, Dafny proves the array lemma as well.

```
lemma mwe_array(e: array<Enum>)
    requires e.Length > 0
    ensures !e[0].A? ==> e[0].B? || e[0].C?
{ }
```

**Comment by layus** [comment]
It works indeed! Thanks for the fast feedback :-)
