### ISSUE TITLE
Post-condition using boolean values in constructor not verified by Dafny

### ISSUE THREAD

**Issue by costaseco** [Microsoft/dafny#194]
When using a boolean instance variable, starting with false, the post-condition is not verified. If the value assigned in the constructor is false, it validates the post-condition. See example below.

I'm using the Dafny Server that is installed by default with the Dafny VSCode Extension (0.11.1). The result is the same using the command line tool version (2.1.1.10209).

```
class A {
    var b:bool;
    constructor() 
        ensures b == false // Cannot prove this post-condition
    {
        b := false;
    }
}

class B {
    var b:bool;
    constructor() 
        ensures b == true // Proves this one
    {
        b := true;
    }
}
```

**Comment by wilcoxjay** [comment]
This is a fascinating bug :) In addition to strangely treating `false` as different from `true`, it is *only* reproducible for fields of type `bool`.

The explanation is that there is a subtle problem in Dafny's encoding of allocatedness, via the Boogie-level field `alloc`. Since `alloc` also has type `bool`, Z3 can't distinguish it from other fields of type `bool`. Typically, two user-declared fields are distinguishable to Z3 via the Boogie-level encoding of `NameFamily`, but `alloc` is not declared to have any `NameFamily`.

I propose the fix of adding a (unique) `NameFamily` for `alloc`, which will then automatically distinguish it from other fields. 

Concretely, I propose adding the following lines to `BoogiePrelude`:

    const unique allocName : NameFamily;
    axiom DeclName(alloc) == allocName;

@RustanLeino can you comment on whether this is the right approach? I'm not really familiar with the `NameFamily` aspect of Dafny's encoding into Boogie.

**Comment by RustanLeino** [comment]
I agree this is fascinating. Thanks for the bug report and the proposed diagnosis. I am currently on vacation (without a laptop) and am looking forward to looking into this when I come home.

**Comment by RustanLeino** [comment]
I forgot to mention that if you're not building Dafny from source and want a workaround, you can write:

```
class A {
    var b: bool
    constructor() 
        ensures b == false
    {
        new;
        b := false;
    }
}
```

That is, initialize boolean fields after the `new;` in the constructor.

**Comment by costaseco** [comment]
Thanks for the quick fix! I will let my students know of the bug fix and the workaround.
