### ISSUE TITLE
Dafny crashes on update to instance of generic type

### ISSUE THREAD

**Issue by jaylorch** [Microsoft/dafny#214]
The following code causes Dafny to crash:

```

module Test {
  datatype GenericType<T> = GenericType(value:T)

  type ConcreteType = GenericType<int>

  function F(c:ConcreteType) : ConcreteType
  {
    c.(value := 0)
  }
}

```

The crash is due to:

Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

This happens because ResolveDatatypeUpdate calls TypeSubstitutionMap with formals equal to the type arguments of GenericType<T> and actuals equal to the type arguments of ConcreteType.  This violates the function's contract, which requires that the arguments' two type argument counts must be equal.  (Here, they're 1 and 0, respectively.)  So Dafny crashes when TypeSubstitutionMap tries to read actuals[i] in the first iteration of the loop when i == 0 < formals.Count.

**Comment by wilcoxjay** [comment]
I have a potential patch here: https://github.com/Microsoft/dafny/compare/issue-214

I pushed it to a branch because I have no idea what I'm doing. I just remember sometimes Rustan fixes these kinds of bugs by adding NormalizeExpand in seemingly random places. I'm doing my best to mimic him. :)

It fixes the specific issue in the program you posted, but YMMV in larger programs. I haven't even run the tests!

**Comment by RustanLeino** [comment]
Thanks for the bug report and the fix. I double check the fix and it is good.

Normalize skips past type proxies, which are temporary types that are used until type inference fills them in.
NormalizeExpandKeepConstraints skips past type proxies and type synonyms.
NormalizeExpand skips past type proxies, type synonyms, and subset types.
