### ISSUE TITLE
Automatic lemmas

### ISSUE THREAD

**Issue by layus** [Microsoft/dafny#231]
Hi @RustanLeino,

Is there a way in Dafny to mark a lemma as "automatic" and add it to the knowledge base of z3 ?

For student homeworks, we often stumble on specifications that are just a bit too complex for Dafny to prove, and require some hand-crafted asserts or lemmas.

It would be nice if we could define those lemmas to augment boogie/z3 search space with domain-specific knowledge, avoiding the need to explain to our students how lemmas work, and the tedious and difficult task to find and use the required lemmas.

Is something like an {:auto} annotation feasible ? Can we augment the .bpl axiomatization ?

**Comment by RustanLeino** [comment]
Hi @layus,

No, there's no such feature in Dafny. (VCC had such a feature, for example.) In some situations, such automation may work well. In other situations, it may cause the lemma to be invoked too many times (say, an infinite number of times), which is problematic.

If you have an interest in trying out some kind of `{:autoLemma}` feature, please feel free to play around with the open Dafny sources. In the present state, I have three suggestions that you may try, and which may alleviate some of the tedium you're experiencing.

One suggestion is to create an "uber lemma" that collects the statements of several other lemmas. For example, if you already have:

    lemma Lemma0(x: X) ensures P0(x) { ... }
    lemma Lemma1(x: X) ensures P1(x) { ... }
    lemma Lemma2(x: X) ensures P2(x) { ... }

then you can combine them into one:

    lemma Everything(x: X)
      ensures P0(x) && P1(x) && P2(x)
    {
      Lemma0(x: X);
      Lemma1(x: X);
      Lemma2(x: X);
    }

This lets you get all 3 properties by calling a single lemma.

Another suggestion is to invoke a lemma on many values at the same time. Given:

    lemma LemmaForOneX(x: X) ensures P(x) { ... }

you can invoke this lemma for all values of `X` simultaneously:

    forall x {
      LemmaForOneX(x);
    }

By placing this `forall` statement at the beginning of some code you're trying to prove, you have in effect called it for every imaginable value of `X`. You can of course also tuck this statement into a lemma of its own and then call this one lemma:

    lemma LemmaForEveryX()
      ensures forall x :: P(x)
    {
      forall x {
        LemmaForOneX(x);
      }
    }

In many cases, this will work fine. In other cases, the verifier may not realize that you have called the lemma on the value that needs the individual lemma, so you may still need to invoke `LemmaForOneX` manually. Also, Dafny takes measure to avoid "matching loops" in the quantifiers generated for the lemma calls above ("matching loops" are what can cause an infinite number of uses of the lemmas). However, the mechanism is not perfect, so this added automation may in some cases cause degraded performance.

A third suggestion is to declare some of the most useful properties of a function in the postcondition of the function, rather than in a separate lemma. For example, instead of:

    function F(x: X): int { ... }
    lemma AboutF(x: X)
      ensures F(x) % 2 == 0
    { ... }

you can declare:

    function F(x: X): int
      ensures F(x) % 2 == 0
    { ... }

To obtain the property stated by the lemma, you must call the lemma. In contrast, any property stated in the postcondition of a function is automatically applied every time you call the function.

As I've mentioned, more information can help the verifier do more things automatically, but too much information cal also overwhelm and confuse the verifier. Therefore, my suggestion is to use function postconditions only for those properties that you think every user of the function will need. Properties needed more rarely are better off declared in lemmas that have to be manually invoked.

Also, there are limits to what you can write in a function postcondition. In particular, what you write must "terminate". In practice, this means you may have problems mentioning the function applied to other arguments in the postcondition. For example,

    predicate R(x: X, y: X)
      ensures R(x, y) <==> R(y, x)  // commutativity
      ensures forall z :: R(x, z) && R(z, y) ==> R(x, y)  // transitivity

is not admitted, because there are self-referential non-terminating (that is, infinitely recursive) calls in the postcondition. Thus, properties like commutativity and transitivity always need to be stated as separate lemmas.

Hope this helps.

  Rustan

PS. Usage questions like these are better posted on Stackoverflow, where they are more easily discoverable by others who may have the same question.
