### ISSUE TITLE
Revealing an opaque function doesn't work if it calls another opaque function

### ISSUE THREAD

**Issue by jaylorch** [Microsoft/dafny#56]
If an opaque function calls another opaque function, then revealing the outer function doesn't allow Dafny to see the revealed function's body.  In the example below, Dafny can't see the obvious fact that BitwiseDiv32(x, y) is equivalent to the expansion of BitwiseDiv32, even after we give it reveal_BitwiseDiv32.

Incidentally, there is a workaround:  setting fuel of 0 for the inner opaque function (e.g., by removing the comment markers below).

type uint32 = i:int | 0 <= i < 0x1_0000_0000

function {:opaque} BitsToWord(b:bv32) : uint32 { b as uint32 }
function {:opaque} WordToBits(u:uint32) : bv32 { u as bv32 }

function {:opaque} BitwiseDiv32(x:uint32, y:uint32):uint32
{
    if WordToBits(y) == 0 then 0 else BitsToWord(WordToBits(x) / WordToBits(y))
}

lemma /*{:fuel WordToBits,0}*/ lemma_UnwrapBitwiseDiv32(x:uint32, y:uint32, z:uint32)
    requires z == BitwiseDiv32(x, y);
    ensures  z == if WordToBits(y) == 0 then 0 else BitsToWord(WordToBits(x) / WordToBits(y));
{
    reveal_BitwiseDiv32();
}

**Comment by qunyanm** [comment]
From email discussion with Chris-Hawblitzel
"I see this as a timeout rather than an error.  For example, if you change the code to use 8-bit integers instead of 32-bit integers, then it succeeds.  It's not surprising that reasoning about 32-bit bit-vector division times out.  The fuel attribute happens to work around the bit-vector timeout."

**Comment by jaylorch** [comment]
Ah, good point.
