### ISSUE TITLE
reveal inside a function body "leaks out", requiring its callers to use the same reveal

### ISSUE THREAD

**Issue by 0xabu** [Microsoft/dafny#63]
The following Dafny fails to verify, unless the reveal line at the end of the lemma is uncommented:
```
type globalsmap = map<string, seq<int>>

predicate {:axiom} ValidGlobal(g:string)

predicate {:opaque} ValidGlobalStateOpaque(globals: globalsmap)
{
    forall g :: ValidGlobal(g) <==> g in globals && |globals[g]| == 1
}

function GlobalWord(gm:globalsmap, g:string): int
    requires ValidGlobalStateOpaque(gm) && ValidGlobal(g)
{
    reveal_ValidGlobalStateOpaque();
    gm[g][0]
}

function GlobalUpdate(gm: globalsmap, g:string, v:int): globalsmap
    requires ValidGlobalStateOpaque(gm) && ValidGlobal(g)
    ensures ValidGlobalStateOpaque(GlobalUpdate(gm, g, v))
{
    reveal_ValidGlobalStateOpaque();
    gm[g := gm[g][0 := v]]
}

lemma test()
{
    ghost var gm1:globalsmap;
    ghost var g: string;
    ghost var v: int;
    assume ValidGlobal(g) && ValidGlobalStateOpaque(gm1);
    ghost var gm2 := GlobalUpdate(gm1, g, v);
    //reveal_ValidGlobalStateOpaque();
    assert GlobalWord(gm2, g) == v;
}
```

Unless @parno and I are mistaken, GlobalUpdate and GlobalWord need the reveal for wellformedness, but the caller lemma shouldn't care because it can see the body of each function, yet it fails to see the effect of the update without the reveal. This appears to be an interaction between the opaque, map and seq, since I found that replacing the seq with a single element makes it go away. It may also be related to #56, although there's only one opaque here.

**Comment by qunyanm** [comment]
I think the problem is that the assume statement in test() and the subsequent requires from the call to GlobalUpdate() and GlobalWord() don't have enough fuel to trigger the function definition axiom of ValidGlobalStateOpaque, Therefore, in the call to GlobalWord(gm2,g), it is not guaranteed that gm2[g][0] is valid. I am guessing we failed the index [0], if replacing the seq with a single element works(though the error message didn't say index out of bound). It does seem counter-intuitive to require reveal in test() when it can see the body of GlobalUpdate() and GlobalWord(), but I am not sure how to fix it.

**Comment by 0xabu** [comment]
Here's another even simpler instance, which I think is the same underlying bug:

```
datatype reg = R0|R1|R2|R3

predicate {:opaque} ValidRegState(regs:map<reg, int>)
{
    forall r:reg :: r in regs
}

function sp_update_reg(r:reg, sM:map<reg, int>, sK:map<reg, int>): map<reg, int> 
    requires ValidRegState(sK) && ValidRegState(sM)
    ensures ValidRegState(sp_update_reg(r, sM, sK))
{
    reveal_ValidRegState();
    sK[r := sM[r]]
}

lemma test() {
    var s0, s1;
    assume ValidRegState(s0) && ValidRegState(s1);
    assume s0 == s1;
    var r: reg;
    //reveal_ValidRegState();
    assert s0 == sp_update_reg(r, s1, s0);
}
```
