### ISSUE TITLE
bitvector cast results in unexpected assertion violation

### ISSUE THREAD

**Issue by rsinha** [Microsoft/dafny#68]
Am I understanding the semantics of `as` operator incorrectly? Running dafny with compile:3 prints out the value 7, but the assertion is not verified. On a related note, are there bitvector concatenation and extraction operators?

```
class Driver
{
    method test2(x: bv4) returns (y: bv8)
    {
       y := x as bv8;
    }
    method Main()
    {
        var testIn : bv4 := 7;
        var testOut := test2(testIn);
        print testOut; print '\n';
        assert testOut == 7;
    }
}
```

**Comment by jaylorch** [comment]
The problem is that there's no post-condition on your method test2 that constrains its behavior. A caller of a method doesn't get to peer into that method's implementation to see what it may do; the caller can only rely on the callee's specification. You can get your program to verify by just putting the following post-condition on method test2:

        ensures y == x as bv8;

**Comment by jaylorch** [comment]
I forgot to answer your "related note" before I closed the issue, sorry. I don't know of any bitvector concatenation or extraction operators, but I'll leave the issue open in case someone else does.

**Comment by rsinha** [comment]
Ah, of course! So sorry we overlooked that. Thanks for your response.

**Comment by parno** [comment]
Z3 supports extraction on bit vectors, but I don't think Dafny does.  If it's something you think would be useful, you could open a separate issue as a feature request (or even better, submit a patch!).
