### ISSUE TITLE
Unstable verification time

### ISSUE THREAD

**Issue by pramod** [Microsoft/dafny#71]
We have a small dafny program with a few simple assertions that exhibits surprising verification behavior with Dafny. When the simple assertion on line 35 (```assert pte == paddr2ppn(paddr) << 10```) is commented out, Dafny verifies the program. However, with the assertion included, it seems to hang. We're seeing similar behavior with some other related asserts not included in this snippet. 

Can you please help us debug why this is happening?

```
class RocketMMU
{

    var mem  : map<bv32, bv32>;
    var ptbr : bv32; 

    constructor init()
        modifies this;
    {
        ptbr := *;
        mem := map[];
    }

    function method vaddr2vpn(vaddr : bv32) : bv32 { (vaddr >> 12) }
    function method paddr2ppn(paddr : bv32) : bv32 { (paddr >> 12) }
    function method pte2ppn(pte : bv32) : bv32 { ((pte & 0x0007_ffff >> 10) & 0x1ff)  }
    function method vpn2ptaddr(vpn : bv32) : bv32 reads this { ptbr + (vpn) }

    method load_page_table(vaddr : bv32, paddr : bv32) 
        returns ()
        modifies this
        ensures (vpn2ptaddr(vaddr2vpn(vaddr)) in mem)
    {
        var vpn : bv32 := vaddr2vpn(vaddr);
        var ppn : bv32 := paddr2ppn(paddr);
        var ptindex : bv32 := vpn2ptaddr(vpn);
        var old_ptbr := ptbr;

        var pte : bv32;
        pte := (ppn << 10);
        write(ptindex, pte);
        assert ptbr == old_ptbr;
        assert ptindex == vpn2ptaddr(vaddr2vpn(vaddr));
        assert ptindex in mem;
        assert pte == paddr2ppn(paddr) << 10;
    }
    method write(paddr : bv32, data : bv32) 
        returns ()
        modifies this 
        ensures 
            (ptbr == old(ptbr))                 &&
            (paddr in mem)                      &&
            (mem[paddr] == data)                &&
            (mem == old(mem)[paddr := data])
    {
        mem := mem[paddr := data];
    }
}
```

**Comment by wilcoxjay** [comment]
On my machine, with a modern Dafny and Z3, the assertion on line 35 is irrelevant: the program always times out.

The issue here is that Z3 is thinking too hard about bitvectors. In particular, about bitvector addition.

The correctness of this program boils down to the fact that `vpn2ptaddr` doesn't change as long as 
`ptbr` doesn't change. This follows from the fact that `+` returns equal results given equal arguments.

Unfortunately, it seems that Z3 is reluctant to see this. Instead it spends all its time trying to show (using the theory of bitvectors) that `vpn2ptaddr`'s value doesn't change.

You can nudge Z3 in the right direction by defining a wrapper function for bitvector addition. This helps Z3 because at the solver level, the wrapper function will be an uninterpreted function, and thus will interact properly with the e-graph, allowing it to quickly see that the value doesn't change. Interpreted functions like bitvector addition are typically not added to the e-graph, which can get in the way in cases like this.

Here is a simpler example demonstrating the problem.

```
function method bv32add(x: bv32, y: bv32): bv32
{
    x + y
}

class C {
    var foo: bv32

    function Bar(x: bv32): bv32
        reads this
    {
        // foo + x  // times out
        bv32add(foo, x)  // verifies instantly
    }

    method Havoc()
        modifies this
        ensures foo == old(foo)
    {}

    method Baz(x: bv32)
        modifies this
        ensures Bar(x) == old(Bar(x))
    {
        Havoc();
    }
}
```

You may want to look at [Komodo](https://github.com/Microsoft/Komodo) for further examples of effective use of bitvectors in Dafny.

**Comment by pramodsu** [comment]
Thanks, James.
