### ISSUE TITLE
nondeterminism in definitions

### ISSUE THREAD

**Issue by jiplucap** [Microsoft/dafny#97]
In my current work in Dafny, I must do some cumbersome proofs when nondeterministic element choice is involved. The problems are in a large context but they reduce to prove the bellow lemma Lem
(of course, suppose that G is commutative).

function G<T>(x:T,X:set<T>):set<T>

function F<T> (X:set<T>):set<T>
{
if |X| == 0 then {}
                 else var x :| x in X;
                        G(x,F(X-{x}))
}

lemma Lem<T> (x:T,X:set<T>)
	requires x in X 
	ensures G(x,F(X-{x})) == F(X)

Please, some suggestion?

**Comment by jaylorch** [comment]
The lemma you're trying to prove isn't true. If G isn't commutative, then it's not necessarily the case that the lemma will be true for an arbitrary x chosen in set X. You'll need some axiom about G that says it's commutative.

Another thing to keep in mind is that, when proving the lemma about F, you'll need access to the particular x that F chooses nondeterministically. The way to do this is something like:

if |X| > 0 {
    var x_chosen_by_F :| x_chosen_by_F in X && F(X) == G(x_chosen_by_F, F(X - {x_chosen_by_F}));
    // use commutativity to go from a fact about x_chosen_by_F to a fact about x.
}

**Comment by jiplucap** [comment]
That's was the way I tried, of course with G being commutative, but I don't succeed., maybe I did something wrong. I'll try again. Thanks, Paqui

**Comment by RustanLeino** [comment]
I remember being surprised by these formal details of iterating over sets.  The first problem to overcome is what Jay is providing a solution for, namely picking the same `x` as is picked by the definition of `F`.  I like that way of selecting the `x` in the lemma.  A different way to do it is to put `F`'s choice operation into a separate function, say `PickForF`.  Then, any call to that function will pick the same value as `F`.

```
function PickForF<T> (X: set): T
  requires X != {}
{
  var x :| x in X; x
}

function F (X:set):set
{
  if |X| == 0 then {}
  else var x := PickForF(X);
  G(x,F(X-{x}))
}
```

Once the `x` has been picked the same way, there is still a proof obligation, which, as you both point out above, needs some commutativity property of `G`.  The proof takes some work.  Here is one version of it:

```
function G<T>(x:T,X:set):set

lemma GCommutative<T>(x: T, y: T, S: set)
  ensures G(x, G(y, S)) == G(y, G(x, S))

function F (X:set):set
{
  if |X| == 0 then {}
  else var x :| x in X;
  G(x,F(X-{x}))
}

lemma AddOne<T>(y: T, X: set)
  requires y !in X
  ensures F(X + {y}) == G(y, F(X))
{
  var Y := X + {y};
  // the following x is what is chosen by F(Y)
  var x :| x in Y && F(Y) == G(x, F(Y - {x}));
  if x == y {
    // the x chosen by F(Y) is the y we're given, so we're done
  } else {
    var W := X - {x};
    calc {
      F(X + {y});
    ==  // def. Y
      F(Y);
    ==  // by the way chose x above
      G(x, F(Y - {x}));
    ==  { assert Y - {x} == W + {y}; }
      G(x, F(W + {y}));
    ==  { AddOne(y, W); }
      G(x, G(y, F(W)));
    ==  { GCommutative(x, y, F(W)); }
      G(y, G(x, F(W)));
    ==  { AddOne(x, W); }
      G(y, F(W + {x}));
    ==  { assert W + {x} == X; }
      G(y, F(X));
    }
  }
}

lemma Lem<T>(x:T,X:set)
  requires x in X
  ensures G(x,F(X-{x})) == F(X)
{
  var W := X - {x};
  calc {
    G(x, F(W));
  ==  { AddOne(x, W); }
    F(W + {x});
  ==  { assert X == W + {x}; }
    F(X);
  }
}
```

A proof like this (called `SumDistribution`), and other information about the choose operator, are found in the paper "Compiling Hilbert’s ϵ Operator", http://www.easychair.org/publications/paper/Compiling_Hilberts_epsilon_operator.

  Rustan

PS.  "Issues" on GitHub become more difficult to find after we mark them Closed.  This seems good for bugs and feature requests. If the "Issue" is more like a question, it's probably better to post them with the "Dafny" tag on StackOverflow, since that makes the answers easier to find for others who may have the same questions.

**Comment by jiplucap** [comment]
Thanks. I have read the paper some time ago, but I forgot that there was a  proof like that. I will apply your beatiful proof to my particular F and G. Best, Paqui

**Comment by jaylorch** [comment]
It seems this discussion has concluded.
